import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getFirestore, doc, onSnapshot } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyBCYpQcTm0_37GAUy8FK_vfChk8seFCOKI",authDomain:"mcgriffsrental.firebaseapp.com",projectId:"mcgriffsrental",storageBucket:"mcgriffsrental.firebasestorage.app",messagingSenderId:"511623270295",appId:"1:511623270295:web:d326c6fd852bafa2e6fed2"};
const db=getFirestore(initializeApp(firebaseConfig));
const id=new URLSearchParams(location.search).get('id');
const $=(selector)=>document.querySelector(selector);
const esc=(value='')=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function driveId(url){for(const p of [/[?&]id=([^&]+)/i,/\/d\/([^/?#]+)/i,/googleusercontent\.com\/d\/([^=/?#]+)/i]){const m=String(url||'').match(p);if(m?.[1])return decodeURIComponent(m[1])}return''}
function imageUrl(url){const fid=driveId(url);return fid?`https://lh3.googleusercontent.com/d/${encodeURIComponent(fid)}=w1600`:String(url||'')}
function dateText(value){if(!value)return'';const d=value?.toDate?value.toDate():new Date(value);return Number.isNaN(d.getTime())?'':d.toLocaleString([],{weekday:'long',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function availability(item){const s=String(item.status||'Available').toLowerCase();if(s.includes('maintenance')||s.includes('service'))return['unavailable','Currently unavailable','Temporarily unavailable while being serviced.'];if(s.includes('rent'))return['limited','Currently rented',item.expectedBack?`Expected back ${dateText(item.expectedBack)}.`:'Call for expected availability.'];if(s.includes('reserv'))return['limited','Limited availability','Contact the store to confirm available dates.'];if(s.includes('unavailable'))return['unavailable','Currently unavailable','Contact the store for expected availability.'];return['available','Available','Submit a reservation request for your preferred dates.']}
function addResource(grid,label,url,icon){if(!url)return;grid.insertAdjacentHTML('beforeend',`<a class="resource-card" target="_blank" rel="noopener" href="${esc(url)}"><span>${icon}</span><strong>${esc(label)}</strong><small>Open resource</small></a>`)}
function showError(message){$('#detail-loading').hidden=true;$('#equipment-detail').hidden=true;$('#detail-error').hidden=false;$('#detail-error-message').textContent=message}
function render(item){$('#detail-loading').hidden=true;$('#equipment-detail').hidden=false;document.title=`${item.name||'Equipment'} | McGriff's Equipment Rentals`;$('#detail-name').textContent=item.name||'Rental Equipment';$('#detail-category').textContent=item.category||'Rental Equipment';const [cls,label,note]=availability(item);$('#detail-status').className=`availability ${cls}`;$('#detail-status').textContent=label;$('#detail-availability').textContent=note;$('#detail-description').textContent=item.publicDescription||item.description||item.quickStart||item.beforeYouStart||"Call McGriff's for details and recommended uses.";const photo=imageUrl(item.photoUrl);$('#detail-photo').innerHTML=photo?`<img src="${esc(photo)}" alt="${esc(item.name||'Rental equipment')}">`:'<div class="detail-photo-placeholder">Equipment photo coming soon</div>';const grid=$('#resource-grid');const sections=[['Quick start',item.quickStart,'✓'],['Before you start',item.beforeYouStart,'⚠'],['Included accessories',item.includedAccessories,'＋'],['Before returning',item.beforeReturning,'↩']];sections.filter(([,v])=>v).forEach(([label,value,icon])=>grid.insertAdjacentHTML('beforeend',`<div class="resource-card text-resource"><span>${icon}</span><strong>${esc(label)}</strong><small>${esc(value)}</small></div>`));(item.manualUrls||[]).forEach((r,i)=>addResource(grid,typeof r==='string'?`Owner's Manual ${i+1}`:r.label||`Owner's Manual ${i+1}`,typeof r==='string'?r:r.url,'📖'));(item.videoUrls||[]).forEach((r,i)=>addResource(grid,typeof r==='string'?`How-To Video ${i+1}`:r.label||`How-To Video ${i+1}`,typeof r==='string'?r:r.url,'▶'));(item.safetyDocuments||[]).forEach((r,i)=>addResource(grid,typeof r==='string'?`Safety Document ${i+1}`:r.label||`Safety Document ${i+1}`,typeof r==='string'?r:r.url,'⚠'));if(grid.children.length)$('#detail-resources').hidden=false;$('#detail-request').onclick=()=>{ $('#request-title').textContent=`Request ${item.name||'reservation'}`; $('#request-dialog').showModal();};}
if(!id)showError('No equipment was selected.');else onSnapshot(doc(db,'publicEquipment',id),snap=>{if(!snap.exists())showError('This equipment has not been published yet.');else if(snap.data().portalEnabled===false||snap.data().websitePublished===false)showError('This equipment is not currently published on the customer website.');else render({id:snap.id,...snap.data()})},()=>showError('The equipment information could not be loaded. Please call the store for help.'));
