import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getFirestore, doc, getDoc, collection, addDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyBCYpQcTm0_37GAUy8FK_vfChk8seFCOKI",authDomain:"mcgriffsrental.firebaseapp.com",projectId:"mcgriffsrental",storageBucket:"mcgriffsrental.firebasestorage.app",messagingSenderId:"511623270295",appId:"1:511623270295:web:d326c6fd852bafa2e6fed2"};
const db=getFirestore(initializeApp(firebaseConfig));
const $=id=>document.getElementById(id); const equipmentId=new URLSearchParams(location.search).get('id'); let equipment=null;
function driveId(url){const s=String(url||'');for(const p of [/[?&]id=([^&]+)/i,/\/d\/([^/?#]+)/i,/googleusercontent\.com\/d\/([^=/?#]+)/i]){const m=s.match(p);if(m?.[1])return decodeURIComponent(m[1])}return''}
function photoUrl(url){const id=driveId(url);return id?`https://lh3.googleusercontent.com/d/${encodeURIComponent(id)}=w1200`:String(url||'')}
function requestNumber(){const y=new Date().getFullYear();const stamp=Date.now().toString(36).slice(-5).toUpperCase();const random=Math.random().toString(36).slice(2,5).toUpperCase();return`RR-${y}-${stamp}${random}`}
function localIso(date,time){return`${date}T${time}`}
function setDefaultDates(){const now=new Date();const pickup=new Date(now);pickup.setDate(pickup.getDate()+1);const ret=new Date(pickup);ret.setDate(ret.getDate()+1);const iso=d=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};$('pickup-date').min=iso(now);$('return-date').min=iso(now);$('pickup-date').value=iso(pickup);$('return-date').value=iso(ret);$('pickup-time').value='08:00';$('return-time').value='16:30'}
async function load(){if(!equipmentId){$('request-loading').innerHTML='<h1>No equipment was selected.</h1>';return}try{const snap=await getDoc(doc(db,'publicEquipment',equipmentId));if(!snap.exists())throw new Error('This equipment is not available on the customer website.');equipment={id:snap.id,...snap.data()};$('request-equipment-id').value=equipment.id;$('request-equipment-name').textContent=equipment.name||'equipment';document.title=`Request ${equipment.name||'Equipment'} | McGriff's`;const p=photoUrl(equipment.photoUrl);$('request-equipment-photo').innerHTML=p?`<img src="${p}" alt="${equipment.name||'Rental equipment'}">`:'<span>Equipment photo coming soon</span>';$('request-loading').hidden=true;$('request-content').hidden=false;setDefaultDates()}catch(e){$('request-loading').innerHTML=`<h1>Unable to load equipment</h1><p>${e.message}</p><p>Call <a href="tel:+16416374010">641-637-4010</a> for help.</p>`}}
$('reservation-request-form').addEventListener('submit',async e=>{e.preventDefault();const button=$('submit-request'),error=$('request-error');error.hidden=true;const startAt=localIso($('pickup-date').value,$('pickup-time').value),endAt=localIso($('return-date').value,$('return-time').value);if(new Date(endAt)<=new Date(startAt)){error.textContent='The return date and time must be after the pickup date and time.';error.hidden=false;return}button.disabled=true;button.textContent='Submitting…';const number=requestNumber();try{await addDoc(collection(db,'reservationRequests'),{requestNumber:number,equipmentId:equipment.id,equipmentName:equipment.name||'',equipmentCategory:equipment.category||'',customerName:`${$('first-name').value.trim()} ${$('last-name').value.trim()}`.trim(),firstName:$('first-name').value.trim(),lastName:$('last-name').value.trim(),phone:$('phone').value.trim(),email:$('email').value.trim(),businessName:$('business-name').value.trim(),projectDescription:$('project-description').value.trim(),notes:$('notes').value.trim(),startAt,endAt,status:'Pending',source:'Customer Website',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});$('request-content').hidden=true;$('success-request-number').textContent=number;$('success-email').textContent=$('email').value.trim();$('request-success').hidden=false;scrollTo({top:0,behavior:'smooth'})}catch(err){console.error(err);error.innerHTML='Your request could not be submitted. Please call <a href="tel:+16416374010">641-637-4010</a>. Firebase may need the reservation-request security rule included with this update.';error.hidden=false;button.disabled=false;button.textContent='Submit reservation request'}});load();